# http://travis-ci.org/#!/RDFLib/rdflib
language: python
branches:
  only:
    - master

python:
    # - 2.5
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    # - "pypy"

install:
    # iodate0.4.8 is problematic with Pypy, use fixed version
    - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors --default-timeout 60 ordereddict; pip install --use-mirrors --default-timeout 60 "simplejson"; pip install --use-mirrors --default-timeout 60 "elementtree"; pip install --use-mirrors --default-timeout 60 "html5lib==0.95"; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors --default-timeout 60 ordereddict; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install --use-mirrors --default-timeout 60 -r requirements.py2.txt;  pip install --use-mirrors --default-timeout 60 "html5lib";fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then pip install --use-mirrors --default-timeout 60 -r requirements.py3.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --upgrade "https://bitbucket.org/gjhiggins/isodate/downloads/isodate-0.4.8.tar.gz"; pip install --use-mirrors --default-timeout 60 "elementtree"; fi
    - if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install --use-mirrors --default-timeout 60 coverage coveralls nose-timer && export HAS_COVERALLS=1; fi
    - python setup.py install

before_script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then flake8 --exclude=pyRdfa,extras,host,transform,rdfs,sparql,results,pyMicrodata --exit-zero rdflib; fi

script:
    # Must run the tests in build/src so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version in build/src.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then nosetests --with-timer --timer-top-n 42 --with-coverage --cover-tests --cover-package=rdflib ; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then nosetests --with-timer --timer-top-n 42 --with-coverage --cover-tests --cover-package=build/src/rdflib --where=./build/src; fi

after_success:
    - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi

notifications:
    irc:
        channels: "chat.freenode.net#rdflib"
